<a href="https://colab.research.google.com/github/Hencynijan/AIproject/blob/main/NijanBhujel_2407973.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Create a Python program that converts between different units of measurement.

In [ ]:
def convert_meters_to_feet(meters):
    """Converts meters to feet and prints the result.

    Parameters:
        meters (float): The value in meters to convert.
    """
    one_meter = 3.28084  # Conversion factor: 1 meter = 3.28084 feet
    feet = meters * one_meter
    print(f"{meters} meters is equal to {feet} feet.")

In [ ]:
def convert_feet_to_meters(feet):
    """Converts feet to meters and prints the result.

    Parameters:
        feet (float): The value in feet to convert.
    """
    one_meter = 3.28084  # Conversion factor: 1 meter = 3.28084 feet
    meters = feet / one_meter
    print(f"{feet} feet is equal to {meters} meters.")

In [ ]:
def kg_to_pound(kg):
    """Converts kilograms to pounds and prints the result.

    Parameters:
        kg (float): The value in kilograms to convert.
    """
    one_kg = 2.20462  # Conversion factor: 1 kilogram = 2.20462 pounds
    pound = kg * one_kg
    print(f"{kg} kilograms is equal to {pound} pounds.")

In [ ]:
def pound_to_kg(pound):
    """Converts pounds to kilograms and prints the result.

    Parameters:
        pound (float): The value in pounds to convert.
    """
    one_kg = 2.20462  # Conversion factor: 1 kilogram = 2.20462 pounds
    kg = pound / one_kg
    print(f"{pound} pounds is equal to {kg} kilograms.")

In [ ]:
def litre_to_gallons(litre):
    """Converts litres to gallons and prints the result.

    Parameters:
        litre (float): The value in litres to convert.
    """
    one_litre = 0.264172  # Conversion factor: 1 litre = 0.264172 gallons
    gallons = litre * one_litre
    print(f"{litre} litres is equal to {gallons} gallons.")

In [ ]:
def gallons_to_litre(gallons):
    """Converts gallons to litres and prints the result.

    Parameters:
        gallons (float): The value in gallons to convert.
    """
    one_litre = 0.264172  # Conversion factor: 1 litre = 0.264172 gallons
    litre = gallons / one_litre
    print(f"{gallons} gallons is equal to {litre} litres.")

In [ ]:
def main():
    """Presents a menu for unit conversions and executes the selected operation."""
    print("Welcome to the Unit Converter")
    print("1. Convert meters to feet")
    print("2. Convert feet to meters")
    print("3. Convert kilograms to pounds")
    print("4. Convert pounds to kilograms")
    print("5. Convert litres to gallons")
    print("6. Convert gallons to litres")
    choice = input("Enter your choice (1-6): ")
    try:
        if choice == "1":
            meters = float(input("Enter the value in meters: "))
            convert_meters_to_feet(meters)
        elif choice == "2":
            feet = float(input("Enter the value in feet: "))
            convert_feet_to_meters(feet)
        elif choice == "3":
            kg = float(input("Enter the value in kilograms: "))
            kg_to_pound(kg)
        elif choice == "4":
            pound = float(input("Enter the value in pounds: "))
            pound_to_kg(pound)
        elif choice == "5":
            litre = float(input("Enter the value in litres: "))
            litre_to_gallons(litre)
        elif choice == "6":
            gallons = float(input("Enter the value in gallons: "))
            gallons_to_litre(gallons)
        else:
            print("Invalid choice. Please enter a number between 1 and 6.")
    except ValueError:
        print("Invalid input. Please enter a valid number.")

In [ ]:
# Execute the main function to run the unit converter program.
main()

Welcome to the Unit Converter
1. Convert meters to feet
2. Convert feet to meters
3. Convert kilograms to pounds
4. Convert pounds to kilograms
5. Convert litres to gallons
6. Convert gallons to litres
Enter your choice (1-6): 5
Enter the value in litres: 5
5.0 litres is equal to 1.3208600000000001 gallons.


#Create a Python program that performs various mathematical operations on a list of numbers.

In [ ]:
def sum_of_numbers(values):
    """Calculates and prints the sum of all numbers in a list.

    Parameters:
        values (list): A list of numerical values.

    Returns:
        float: The total sum of the numbers.
    """
    sum = 0
    for value in values:
        # Corrected indexing: directly add 'value' instead of 'values[value - 1]'
        sum += value
    print(f"The total sum of given number is {sum}")
    return sum

In [ ]:
def average_of_numbers(values):
    """Calculates and prints the average of numbers in a list.

    Parameters:
        values (list): A list of numerical values.
    """
    sum = sum_of_numbers(values)
    average = sum/len(values)
    print(f"Average of given number is {average}")

In [ ]:
def maximum_of_numbers(values):
    """Finds and prints the maximum value in a list of numbers.

    Parameters:
        values (list): A list of numerical values.
    """
    maximum = values[0]
    for value in values:
        if value > maximum:
            maximum = value
    print(f"Maximum of given number is {maximum}")

In [ ]:
def minimum_of_numbers(values):
    """Finds and prints the minimum value in a list of numbers.

    Parameters:
        values (list): A list of numerical values.
    """
    min_val = values[0] # Renamed variable 'min' to 'min_val' to avoid shadowing built-in function
    for value in values:
        if value < min_val:
            min_val = value
    print(f"Minimum of given number is {min_val}")

In [ ]:
def main():
    """Provides an interactive menu for mathematical operations on a list of numbers."""
    # ask for user input
    print("Welcome to the program that performs various mathematical operations on a list of numbers.")
    try:
        list_of_numbers = [int(x) for x in input("Enter list of numbers (space separated): ").split()]
    except ValueError:
        print("Invalid input. Please enter numbers separated by spaces.")
        return

    print("We have different operations:")
    print("1. Sum of numbers")
    print("2. Average of numbers")
    print("3. Maximum of numbers")
    print("4. Minimum of numbers")
    choice = input("Enter your choice (1-4): ")

    try:
        if choice == "1":
            sum_of_numbers(list_of_numbers)
        elif choice == "2":
            average_of_numbers(list_of_numbers)
        elif choice == "3":
            maximum_of_numbers(list_of_numbers)
        elif choice == "4":
            minimum_of_numbers(list_of_numbers)
        else:
            print("Invalid choice. Please enter a number between 1 and 4.")
    except Exception as e:
        print(f"An error occurred: {e}")

In [ ]:
main() # Execute the main function to run the mathematical operations program.

Welcome to the program that performs various mathematical operations on a list of numbers.
Enter list of numbers (space separated): 1 2 3 4 5 
We have different operations:
1. Sum of numbers
2. Average of numbers
3. Maximum of numbers
4. Minimum of numbers
Enter your choice (1-4): 1
The total sum of given number is 15


#Write a Python function that extracts every other element from a list, starting from the first element.

In [ ]:
def extract_every_other(lst):
    """Extracts every other element from a list, starting from the first element.

    Parameters:
        lst (list): The input list.

    Returns:
        list: A new list containing every other element.
    """
    return lst[::2]

In [ ]:
# Example usage of extract_every_other function.
input_value = [1, 2, 3, 4, 5]
extract_every_other(input_value)

[1, 3, 5]

#Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.

In [ ]:
def get_sublist(lst, start_index, end_index):
    """Returns a sublist from a given list, starting from a specified index
    and ending at another specified index (inclusive).

    Parameters:
        lst (list): The input list.
        start_index (int): The starting index of the sublist.
        end_index (int): The ending index of the sublist (inclusive).

    Returns:
        list: The extracted sublist.
    """
    return lst[start_index : end_index + 1]

In [ ]:
# Example usage of get_sublist function.
input = [1,2,3,4,5,6]
get_sublist(input, 1,3)

[2, 3, 4]

#Write a Python function that reverses a list using slicing.


In [ ]:
def reverse_list(lst):
    """Reverses a list using slicing.

    Parameters:
        lst (list): The input list.

    Returns:
        list: The reversed list.
    """
    return lst[::-1]

In [ ]:
# Example usage of reverse_list function.
input = [1,2,3,4,5,6]
reverse_list(input)

[6, 5, 4, 3, 2, 1]

#Write a Python function that removes the first and last elements of a list and returns the resulting sublist.

In [ ]:
def remove_first_last(lst):
    """Removes the first and last elements of a list and returns the resulting sublist.

    Parameters:
        lst (list): The input list.

    Returns:
        list: The list with the first and last elements removed.
    """
    # Corrected slicing to remove the first and last elements
    return lst[1:-1]

In [ ]:
# Example usage of remove_first_last function.
input = [1,2,3,4,5,6,7,8,9]
remove_first_last(input)

[2, 3, 4, 5, 6, 7, 8]

#Write a Python function that extracts the first n elements of a list using slicing.

In [ ]:
def get_first_n(lst, n):
    """Extracts the first n elements of a list using slicing.

    Parameters:
        lst (list): The input list.
        n (int): The number of elements to extract from the beginning.

    Returns:
        list: A new list containing the first n elements.
    """
    # Corrected slicing to get the first n elements
    return lst[:n]

In [ ]:
# Example usage of get_first_n function.
input = [1,2,3,4,5,6,7,8,9]
get_first_n(input, 3)

[1, 2, 3]

#Write a Python function that extracts the last n elements of a list using slicing.

In [ ]:
def get_last_n(lst, n):
    """Extracts the last n elements of a list using slicing.

    Parameters:
        lst (list): The input list.
        n (int): The number of elements to extract from the end.

    Returns:
        list: A new list containing the last n elements.
    """
    # Corrected slicing to get the last n elements
    return lst[-n:]

In [ ]:
# Example usage of get_last_n function.
input = [1,2,3,4,5,6,7,8,9]
get_last_n(input, 3)

[7, 8, 9]

#Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

In [ ]:
def reverse_skip(lst):
    """Extracts every other element starting from the first, then reverses the resulting list.

    Parameters:
        lst (list): The input list.

    Returns:
        list: A new list with every other element, reversed.
    """
    skip_val = lst[::2]
    return skip_val[::-1]

In [ ]:
def reverse_skip_better(lst):
    """Extracts elements in reverse order, starting from the second-to-last element
    and skipping one element in between.

    Parameters:
        lst (list): The input list.

    Returns:
        list: A new list with elements extracted in reverse and skipped.
    """
    return lst[-2::-2]

In [ ]:
# Example usage of reverse_skip function.
reverse_skip([1, 2, 3, 4, 5, 6, 7])

[7, 5, 3, 1]

In [ ]:
# Example usage of reverse_skip_better function.
reverse_skip_better([1, 2, 3, 4, 5, 6, 7])

[6, 4, 2]

#Exercise on Nested List

1. Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

In [ ]:
def flatten(lst):
  """Flattens a list of lists into a single list.

  Parameters:
    lst (list): A nested list (e.g., [[1, 2], [3, 4]]).

  Returns:
    list: A new list containing all elements in a single dimension.
  """
  flat = [item for i in lst for item in i]
  print(flat)

nested_list = [[1, 2], [3, 4], [5]]
flatten(nested_list)

[1, 2, 3, 4, 5]


2. Write a Python function that extracts a specific element from a nested list given its indices.

In [ ]:
def access_nested_elements(lst, indices):
  """Extracts a specific element from a nested list given its indices.

  Parameters:
    lst (list): The nested list.
    indices (list): A list of integers representing the path to the element.

  Returns:
    any: The element at the specified nested indices.
  """
  value = lst
  for i in indices:
    # print(i) # Removed debug print
    value = value[i]
  return value

In [ ]:
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2 ]
access_nested_elements(lst, indices)

6

3. Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

In [ ]:
def sum_nested(lst):
  """Calculates the sum of all numbers in a nested list (regardless of depth).

  Parameters:
    lst (list): The nested list to sum.

  Returns:
    int or float: The total sum of all numbers.
  """
  total = 0
  for item in lst:
    if isinstance(item, list):
      total += sum_nested(item)
    else:
      total += item
  return total

In [ ]:
lst = [[1, 2], [3, [4, 5]], 6]
sum_nested(lst)

21

4. Remove Specific Element from a Nested List:


In [ ]:
def remove_element(lst , elem):
  """Removes a specific element from a nested list. The element is removed
  from each sublist where it is found.

  Parameters:
    lst (list): The nested list.
    elem (any): The element to remove.

  Returns:
    list: The modified nested list.
  """
  # Note: This implementation modifies the sublists in place.
  # If a completely new list structure is required, deep copying and reconstruction would be needed.
  new_lst = []
  for sublist in lst:
      if isinstance(sublist, list):
          new_sublist = [item for item in sublist if item != elem]
          new_lst.append(new_sublist)
      else:
          # Handle cases where the top-level list might contain non-list elements
          if sublist != elem:
              new_lst.append(sublist)
  return new_lst

In [ ]:
lst = [[1, 2], [3, 2], [4, 5]]
remove_element(lst, 2)

[[1], [3], [4, 5]]

5. Write a Python function that finds the maximum element in a nested list (regardless of depth).

In [ ]:
def find_max(lst):
    """Finds the maximum element in a nested list (regardless of depth).

    Parameters:
        lst (list): The nested list.

    Returns:
        int or float: The maximum numerical value found in the list.
    """
    max_value = -float('inf') # Initialize with negative infinity for robust comparison

    for item in lst:
        if isinstance(item, list):
            value = find_max(item)
        else:
            value = item

        if value > max_value:
            max_value = value

    return max_value

In [ ]:
lst = [[1, 2], [3, [4, 5]], 6]
find_max(lst)

6

6. Write a Python function that counts how many times a specific element appears in a nested list.

In [ ]:
def count_occurance(lst, elem):
  """Counts how many times a specific element appears in a nested list (regardless of depth).

  Parameters:
    lst (list): The nested list.
    elem (any): The element to count.

  Returns:
    int: The total count of the element in the nested list.
  """
  count = 0
  for item in lst:
    if isinstance(item, list):
      count += count_occurance(item, elem) # Recursively count in sublists
    elif item == elem:
      count += 1
  return count

In [ ]:
lst = [[1, 2], [2, 3], [2, 4], 2]
elem = 2
count_occurance(lst, elem)

4

7. Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

In [ ]:
def deep_flatten(lst):
  """Flattens a list of lists of lists into a single list, regardless of the depth.

  Parameters:
    lst (list): The nested list to flatten.

  Returns:
    list: A new list containing all elements in a single dimension.
  """
  flat_list = []
  for item in lst:
    if isinstance(item, list):
      flat_list.extend(deep_flatten(item))
    else:
      flat_list.append(item)
  return flat_list

In [ ]:
lst = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
deep_flatten(lst)

[1, 2, 3, 4, 5, 6, 7, 8]

8. Write a Python function that calculates the average of all elements in a nested list.

In [ ]:
def average_nested(lst):
  """Calculates the average of all elements in a nested list (regardless of depth).

  Parameters:
    lst (list): The nested list containing numerical values.

  Returns:
    float: The average of all numbers in the nested list.
  """
  flat_list = deep_flatten(lst) # Use the deep_flatten function
  if not flat_list:
      return 0.0 # Handle empty list case to avoid division by zero
  total_sum = sum(flat_list)
  average = total_sum / len(flat_list)
  return average

In [ ]:
lst = [[1, 2], [3, 4], [5, 6]]
average_nested(lst)

3.5

In [ ]:
import numpy as np # Import the NumPy library, essential for numerical operations.

# Basic Vector and Matrix Operation with Numpy.

In [ ]:
# Create a 2x2 array filled with zeros.
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
# Create a 4x2 array filled with ones.
np.ones((4, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# Create a 3x4 array filled with a constant value (7), specifying integer data type.
arr = np.full((3, 4), 7, dtype=int)
print(arr)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
# Create an array of zeros with the same shape and data type as an existing array.
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
zeros_arr = np.zeros_like(arr)
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Create an array of ones with the same shape and data type as an existing array.
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
zeros_arr = np.ones_like(arr)
print(zeros_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Convert a Python list to a NumPy array.
new_list = [1,2,3,4]
np.array(new_list)

array([1, 2, 3, 4])

# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:
# Generate a 1D array containing numbers from 10 up to (but not including) 49.
np.arange(10, 49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [ ]:
# Create a 1D array from 0 to 8, then reshape it into a 3x3 2D array (matrix).
array_arange = np.arange(0, 9)
np.reshape(array_arange , (3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Create a 3x3 identity matrix, which has ones on the main diagonal and zeros elsewhere.
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Generate a 1D array of 30 random floats between 0 and 1, then compute their mean.
random_array = np.random.random(30)
np.mean(random_array)

np.float64(0.4325137627132739)

In [ ]:
# Create a 10x10 array of random floats and find its maximum and minimum values.
random_floats_array = np.random.rand(10, 10)
print("Max values =", np.max(random_floats_array))
print("Min Values =", np.min(random_floats_array))

Max values = 0.9915934264496036
Min Values = 0.000952257997627326


In [ ]:
# Create a 1D array of 10 zeros and set the 6th element (index 5) to 1.
zero_array = np.zeros(10)
zero_array[5] = 1
print(zero_array)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [ ]:
# Convert a Python list to a NumPy array and then reverse its elements.
lst_to_convert = [1,2,0,0,4,0]
np_array_from_list = np.array(lst_to_convert)
print(np.flip(np_array_from_list))

[0 4 0 0 2 1]


In [ ]:
# Create a 5x5 array of zeros and set the border elements to ones.
border_array = np.zeros((5,5))
border_array[0 , :] = 1 # Top row
border_array[:, 0] = 1 # Left column
border_array[:, -1] = 1 # Right column
border_array[-1, :] = 1 # Bottom row

print(border_array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Create an 8x8 array representing a chessboard pattern (alternating zeros and ones).
chessboard_array = np.zeros((8,8))
chessboard_array[::2, ::2] = 1 # Set '1's on even rows and even columns
chessboard_array[1::2, 1::2] = 1 # Set '1's on odd rows and odd columns
print(chessboard_array)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


# Problem - 3: Array Operations:

In [ ]:
# Define two 2x2 matrices (x, y) and two 1D vectors (v, w) for subsequent operations.
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

In [ ]:
# Perform element-wise addition of two matrices.
np.add(x, y)

array([[ 6,  8],
       [10, 13]])

In [ ]:
# Perform element-wise subtraction of two matrices.
np.subtract(x, y)

array([[-4, -4],
       [-4, -3]])

In [ ]:
# Calculate the dot product of two 1D vectors.
np.dot(v, w)

np.int64(219)

In [ ]:
# Calculate the dot product of a matrix and a vector.
np.dot(x, v)

array([29, 77])

In [ ]:
# Calculate the matrix multiplication (dot product) of two matrices.
np.dot(x, y)

array([[19, 22],
       [50, 58]])

In [ ]:
# Concatenate two matrices along the second axis (columns).
np.concatenate((x, y), axis=1)

array([[1, 2, 5, 6],
       [3, 5, 7, 8]])

In [ ]:
# Concatenate two 1D vectors along the zero axis.
np.concatenate((v, w), axis=0)

array([ 9, 10, 11, 12])

In [ ]:
# Attempt to concatenate a 2D matrix (x) with a 1D vector (v) along axis=0.
# This will result in a ValueError because arrays must have the same number of dimensions.
# To resolve this, `v` can be reshaped to a 2D array before concatenation.
# Example of correction:
# np.concatenate((x, v.reshape(1, -1)), axis=0)
np.concatenate((x, v), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

# Problem - 4: Matrix Operations

In [ ]:
# Define two 2x2 matrices A and B for matrix operations.
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [ ]:
# Compute the transpose of matrices A and B.
A_T = A.T
B_T = B.T

In [ ]:
# Calculate the inverse of matrix A and verify the property A * A_inv = I (Identity Matrix).
# compute inverse
A_inv = np.linalg.inv(A)
# multiply A by its inverse
result = np.dot(A, A_inv)
print("A * A_inv:\n", result)

# compare with identity matrix
I = np.eye(2)
print("Identity matrix:\n", I)

# check if result is close to identity (due to floating point errors)
print("Are they equal? ", np.allclose(result, I))

A * A_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity matrix:
 [[1. 0.]
 [0. 1.]]
Are they equal?  True


In [ ]:
# Demonstrate that matrix multiplication is generally not commutative (AB != BA).
a_dot_b = np.dot(A, B)
b_dot_a = np.dot(B, A)

np.equal(a_dot_b, b_dot_a)

array([[False, False],
       [False, False]])

Prove (AB)T = BTAT

In [ ]:
# Compute (AB)^T and B^T A^T to prove their equality.
AB_T = a_dot_b.T
AB_T_DOT = np.dot(B_T, A_T)

In [ ]:
# Check if the calculated (AB)^T is equal to B^T A^T.
np.equal(AB_T, AB_T_DOT)

array([[ True,  True],
       [ True,  True]])

In [ ]:
# Set up a system of linear equations in matrix form Ax = b.
equation_list = [2, -3, 1, 1, -1, 2, 3, 1, 0] # Coefficients of the equations
b = np.array([-1, -3, 9]) # Constant terms
A = np.array(equation_list).reshape(3, 3) # Coefficient matrix
print(A) # Print the coefficient matrix

[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1  0]]


In [ ]:
# Solve the system of linear equations Ax = b for x using NumPy's linear algebra solver.
x = np.linalg.solve(A, b)
print(x)

[ 2.55555556  1.33333333 -2.11111111]


# Experiment: How Fast is Numpy?

In [ ]:
import time # Import the time module to measure execution time.

# Define a large size for lists and arrays to highlight performance differences.
size = 1_000_000

# Create two large Python lists.
list1 = list(range(size))
list2 = list(range(size))

# Create two equivalent NumPy arrays.
arr1 = np.array(list1)
arr2 = np.array(list2)

In [ ]:
# Compare the time taken for element-wise addition using Python lists and NumPy arrays.
start = time.time()
[ a + b for a, b in zip(list1, list2) ]
print("Python list addition:", time.time() - start)

start = time.time()
arr1 + arr2
print("NumPy addition:", time.time() - start)

Python list addition: 0.142622709274292
NumPy addition: 0.00257110595703125


In [ ]:
# Compare the time taken for element-wise multiplication using Python lists and NumPy arrays.
start = time.time()
[ a * b for a, b in zip(list1, list2) ]
print("Python list multiplication:", time.time() - start)

start = time.time()
arr1 * arr2
print("NumPy multiplication:", time.time() - start)

Python list multiplication: 0.1447584629058838
NumPy multiplication: 0.003139972686767578


In [ ]:
# Compare the time taken for dot product calculation using Python lists and NumPy arrays.
start = time.time()
sum(a * b for a, b in zip(list1, list2))
print("Python list dot product:", time.time() - start)

start = time.time()
np.dot(arr1, arr2)
print("NumPy dot product:", time.time() - start)

Python list dot product: 0.08925867080688477
NumPy dot product: 0.0019366741180419922


In [ ]:
# Compare the time taken for matrix multiplication using NumPy arrays.
# Python's standard library does not have an efficient direct equivalent for matrix multiplication.
size_mat = 500
A_mat = np.random.rand(size_mat, size_mat) # Renamed A to A_mat to avoid conflict with earlier A
B_mat = np.random.rand(size_mat, size_mat) # Renamed B to B_mat to avoid conflict with earlier B

start = time.time()
A_mat @ B_mat
print("NumPy matrix multiplication:", time.time() - start)

NumPy matrix multiplication: 0.00932931900024414
